spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${{ secrets.DATASOURCE_URL }}
    username: ${{ secrets.DATASOURCE_USERNAME }}
    password: ${{ secrets.DATASOURCE_PASSWORD }}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
